-- 면접 중 웹이 녹화한 MP4를 받아 둔 기록.
--
-- 영상 자체는 S3에 있고 여기에는 그 키만 남긴다. 웹은 음성 답변 하나마다 녹화를 끊으므로
-- 한 면접에 여러 행이 생긴다.
CREATE TABLE interview_recording (
    recording_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    interview_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    chat_question_id BIGINT,
    s3_key VARCHAR(512) NOT NULL,
    file_size BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT interview_recording_pkey PRIMARY KEY (recording_id)
);

CREATE INDEX interview_recording_interview_id_idx ON interview_recording (interview_id);

COMMENT ON COLUMN interview_recording.chat_question_id IS
    '녹화 중에 답하던 질문. 웹이 들고 있는 채팅 서버 질문 번호라 interview_question.chat_question_id와 같은 체계다. 질문 행은 면접이 끝나야 생기므로 FK를 걸지 않는다. 웹이 보내지 않으면 비어 있다.';
