-- 면접 녹화를 분석 서버에 넘긴 기록. 면접 하나에 한 번만 보낸다.
--
-- 질문·답변은 채팅 서버가, 영상은 웹이 따로 보내 도착 순서가 정해져 있지 않다. 그래서 기록을
-- 받는 순간 WAITING으로 행을 만들고, 영상이 다 모이거나 한동안 아무것도 오지 않으면 보낸다.
CREATE TABLE recording_analysis (
    analysis_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    interview_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    job_id VARCHAR(64),
    error_message TEXT,
    last_activity_at TIMESTAMP(6) NOT NULL,
    requested_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT recording_analysis_pkey PRIMARY KEY (analysis_id),
    CONSTRAINT recording_analysis_interview_unique UNIQUE (interview_id),
    CONSTRAINT recording_analysis_status_check
        CHECK (status IN ('WAITING', 'SENDING', 'PENDING', 'FAILED', 'SKIPPED'))
);

CREATE INDEX recording_analysis_status_activity_idx ON recording_analysis (status, last_activity_at);

COMMENT ON COLUMN recording_analysis.status IS
    'WAITING: 기록은 받았고 영상을 기다리는 중. SENDING: 보내는 중(한 곳만 차지한다). PENDING: 분석 서버가 접수함. FAILED: 접수 실패. SKIPPED: 기다려도 영상이 하나도 오지 않아 보내지 않음.';

COMMENT ON COLUMN recording_analysis.last_activity_at IS
    '기록이나 영상이 마지막으로 들어온 시각. 영상이 덜 모였을 때 이 시각부터 유예 시간이 지나면 있는 것만 보낸다.';
