CREATE TABLE analysis_data (
    job_id VARCHAR(255) NOT NULL,
    result JSONB,
    CONSTRAINT analysis_data_pkey PRIMARY KEY (job_id)
);

CREATE TABLE persona (
    persona_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    major VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    career INTEGER NOT NULL,
    gender VARCHAR(255) NOT NULL,
    CONSTRAINT persona_pkey PRIMARY KEY (persona_id),
    CONSTRAINT persona_name_unique UNIQUE (name),
    CONSTRAINT persona_major_check CHECK (major IN ('BACKEND', 'FRONTEND')),
    CONSTRAINT persona_type_check CHECK (type IN ('FRIENDLY', 'NEUTRAL', 'STRESS')),
    CONSTRAINT persona_gender_check CHECK (gender IN ('MALE', 'FEMALE'))
);

CREATE TABLE interview (
    interview_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    persona_id BIGINT NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT interview_pkey PRIMARY KEY (interview_id),
    CONSTRAINT interview_session_id_unique UNIQUE (session_id),
    CONSTRAINT interview_status_check CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED'))
);

CREATE TABLE interview_question (
    question_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    interview_id BIGINT NOT NULL,
    parent_id BIGINT,
    type VARCHAR(255) NOT NULL,
    intention VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT interview_question_pkey PRIMARY KEY (question_id),
    CONSTRAINT interview_question_type_check CHECK (type IN ('ORIGINAL', 'FOLLOW'))
);

CREATE TABLE interview_answer (
    answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    interview_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    response_time INTEGER NOT NULL,
    content VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT interview_answer_pkey PRIMARY KEY (answer_id)
);
