-- 답변 음성을 채점 요청에 싣지 않고 분석 서버의 음성 분석(POST /analysis/audio)으로 따로 보낸다.
--
-- 채점(질문·답변)은 면접 기록만 있으면 곧바로 요청하고, 음성 분석은 답변 음성이 모일 때까지 미룬다.
-- 둘 다 같은 대기·재시도 장치를 쓰므로 feedback_dispatch에 종류를 두고 면접마다 종류별로 한 행씩 둔다.
ALTER TABLE feedback_dispatch ADD COLUMN kind VARCHAR(32) NOT NULL DEFAULT 'FEEDBACK';
ALTER TABLE feedback_dispatch ALTER COLUMN kind DROP DEFAULT;
ALTER TABLE feedback_dispatch
    ADD CONSTRAINT feedback_dispatch_kind_check CHECK (kind IN ('FEEDBACK', 'AUDIO_ANALYSIS'));
ALTER TABLE feedback_dispatch DROP CONSTRAINT feedback_dispatch_interview_unique;
ALTER TABLE feedback_dispatch
    ADD CONSTRAINT feedback_dispatch_interview_kind_unique UNIQUE (interview_id, kind);

COMMENT ON COLUMN feedback_dispatch.kind IS
    'FEEDBACK = 질문·답변 채점(/feedback/solo·multi). 면접 기록이 오면 곧바로 요청한다. AUDIO_ANALYSIS = 답변 음성 분석(/analysis/audio). 답한 질문마다 음성이 모이거나 조용해지면 요청한다.';

-- 웹이 답변 녹음을 왜 끝냈는지. 음성 분석이 시간 제한으로 잘린 답변을 가려 보는 데 쓴다.
ALTER TABLE interview_recording ADD COLUMN end_reason VARCHAR(20);
ALTER TABLE interview_recording
    ADD CONSTRAINT interview_recording_end_reason_check
        CHECK (end_reason IS NULL OR end_reason IN ('USER', 'TIMEOUT', 'INTERRUPTED', 'UNKNOWN'));

COMMENT ON COLUMN interview_recording.end_reason IS
    '답변 녹음 종료 이유. USER = 사용자가 직접 종료, TIMEOUT = 답변 시간 제한, INTERRUPTED = 오류·연결 문제로 중단, UNKNOWN = 알 수 없음. 웹이 보내지 않으면 비어 있고 분석 서버에는 unknown으로 넘긴다.';

-- 음성 분석 요청 하나. 분석 서버가 한 번에 12개까지 받아 녹음이 많으면 여러 행으로 나뉜다.
CREATE TABLE audio_analysis (
    analysis_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    interview_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    session_id VARCHAR(64),
    request_id VARCHAR(64) NOT NULL,
    job_id VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    recording_ids JSONB NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT audio_analysis_pkey PRIMARY KEY (analysis_id),
    CONSTRAINT audio_analysis_request_unique UNIQUE (request_id),
    CONSTRAINT audio_analysis_job_unique UNIQUE (job_id),
    CONSTRAINT audio_analysis_status_check
        CHECK (status IN ('PENDING', 'READY', 'PARTIAL', 'UNAVAILABLE', 'FAILED'))
);

CREATE INDEX audio_analysis_interview_id_idx ON audio_analysis (interview_id);

COMMENT ON TABLE audio_analysis IS
    '분석 서버에 맡긴 음성 분석 요청. 결과는 녹음별로 audio_analysis_result에 남는다.';
COMMENT ON COLUMN audio_analysis.request_id IS
    '이 서버가 만든 요청 id. 콜백이 접수 응답보다 먼저 와도 이 값으로 되짚는다.';
COMMENT ON COLUMN audio_analysis.status IS
    'PENDING = 접수됨, 콜백 대기. READY / PARTIAL / UNAVAILABLE = 콜백이 알린 전체 결과의 완전성. FAILED = 콜백이 제때 오지 않음.';
COMMENT ON COLUMN audio_analysis.recording_ids IS
    '이 요청에 실은 interview_recording.recording_id 목록. 다시 요청할 때 이미 맡긴 녹음을 빼는 데 쓴다.';

-- 녹음 하나의 분석 결과. 실패한 녹음도 행이 남는다.
CREATE TABLE audio_analysis_result (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    analysis_id BIGINT NOT NULL,
    recording_id BIGINT,
    question_id BIGINT,
    answer_id BIGINT,
    status VARCHAR(20),
    duration_ms BIGINT,
    timing JSONB,
    fluency JSONB,
    error TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT audio_analysis_result_pkey PRIMARY KEY (result_id),
    CONSTRAINT audio_analysis_result_analysis_fk
        FOREIGN KEY (analysis_id) REFERENCES audio_analysis (analysis_id) ON DELETE CASCADE
);

CREATE INDEX audio_analysis_result_analysis_id_idx ON audio_analysis_result (analysis_id);

COMMENT ON COLUMN audio_analysis_result.status IS
    '분석 서버가 알린 이 녹음의 완전성. ready / partial / unavailable을 대문자로 둔다.';
COMMENT ON COLUMN audio_analysis_result.timing IS
    '말 속도·침묵·속도 안정성. 분석 서버가 보낸 {status, data, error} 그대로.';
COMMENT ON COLUMN audio_analysis_result.fluency IS
    '말 더듬기·간투사·문장 완결성. 분석 서버가 보낸 {status, data, error} 그대로.';
COMMENT ON COLUMN audio_analysis_result.error IS
    '이 녹음의 실패 사유. 문자열이 아니면 JSON 문자열로 둔다.';
