-- 면접 화면 전체 녹화(FULL_INTERVIEW)를 분석 서버의 영상 분석(POST /analysis/video)에 맡긴 기록.
--
-- 음성 분석과 따로 요청·작업·결과를 갖는다. 한 행이 요청 하나이고, 면접의 최종 영상(가장 나중에 기록된
-- FULL_INTERVIEW)만 보낸다. 재분석은 행을 고치지 않고 새 행(새 request_id)으로 남겨, 늦게 온 옛 결과가
-- 새 결과를 덮지 않게 한다.
CREATE TABLE video_analysis (
    analysis_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    interview_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    session_id VARCHAR(64),
    recording_id BIGINT NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    job_id VARCHAR(255),
    chain_id VARCHAR(64) NOT NULL,
    requested_by VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    request_payload JSONB,
    send_count INTEGER NOT NULL DEFAULT 0,
    next_check_at TIMESTAMP(6),
    result JSONB,
    error_code VARCHAR(100),
    error_retryable BOOLEAN,
    error_message TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT video_analysis_pkey PRIMARY KEY (analysis_id),
    CONSTRAINT video_analysis_request_unique UNIQUE (request_id),
    CONSTRAINT video_analysis_job_unique UNIQUE (job_id),
    CONSTRAINT video_analysis_status_check
        CHECK (status IN ('PENDING', 'READY', 'PARTIAL', 'UNAVAILABLE', 'FAILED')),
    CONSTRAINT video_analysis_requested_by_check CHECK (requested_by IN ('AUTO', 'USER'))
);

-- 영상 하나에 살아 있는 요청은 하나뿐이다. 서버가 두 대 떠 있는 배포 중에도, 사용자가 재분석을 연달아 눌러도
-- 같은 영상에 분석이 둘 나가지 않는다. 다른 영상(재업로드)은 막지 않는다.
CREATE UNIQUE INDEX video_analysis_active_recording_idx ON video_analysis (recording_id) WHERE status = 'PENDING';
CREATE INDEX video_analysis_interview_id_idx ON video_analysis (interview_id);
CREATE INDEX video_analysis_chain_id_idx ON video_analysis (chain_id);

COMMENT ON COLUMN video_analysis.recording_id IS
    '분석한 영상. interview_recording.recording_id이고 분석 서버에는 videoId로 넘긴다.';
COMMENT ON COLUMN video_analysis.request_id IS
    '이 서버가 만든 요청 id. 보내기 전에 남긴다. 같은 요청을 다시 보낼 때는 이 값과 request_payload를 그대로 쓴다.';
COMMENT ON COLUMN video_analysis.job_id IS
    '분석 서버가 접수하며 발급한 작업 id. 비어 있으면 보냈지만 202를 받지 못한 요청이다.';
COMMENT ON COLUMN video_analysis.chain_id IS
    '같은 묶음의 요청이 공유하는 값. 처음 요청(자동 또는 사용자 재분석)이 묶음을 열고, 재시도 가능한 실패로 이어 보낸 자동 재분석이 같은 값을 잇는다. 자동 재분석 한도를 묶음 단위로 센다.';
COMMENT ON COLUMN video_analysis.requested_by IS
    'AUTO = 업로드 뒤 자동으로 연 묶음, USER = 사용자가 재분석으로 연 묶음. 묶음의 모든 행이 같은 값을 갖는다.';
COMMENT ON COLUMN video_analysis.status IS
    'PENDING = 결과 대기. READY / PARTIAL / UNAVAILABLE = 분석 서버가 알린 결과의 완전성. FAILED = 결과 없이 닫음(사유는 error_code).';
COMMENT ON COLUMN video_analysis.request_payload IS
    '보낸 요청 본문(서명 URL 포함). 같은 request_id로 다시 보낼 때 이 본문만 보낸다 -- 내용이 바뀌면 분석 서버가 409로 거절한다. 보내기 전에 걸러 닫은 행(세션 없음, 입력 제한 초과 등)은 비어 있다.';
COMMENT ON COLUMN video_analysis.send_count IS
    '이 request_id로 보낸 횟수(처음 포함). 계약상 5회, 처음 보낸 뒤 1시간까지만 다시 보낸다.';
COMMENT ON COLUMN video_analysis.next_check_at IS
    'PENDING일 때 다시 보내거나 작업을 조회할 가장 이른 시각.';
COMMENT ON COLUMN video_analysis.result IS
    '검증을 통과한 콜백 본문(또는 작업 조회로 받은 같은 본문) 원문.';
COMMENT ON COLUMN video_analysis.error_retryable IS
    '참 = 같은 원본으로 새 분석을 하면 살 수 있는 실패(자동 재분석 대상). 거짓 = 영상을 새로 올려야 하는 실패. 비어 있음 = 이 서버가 닫은 실패라 자동으로는 다시 하지 않지만 사용자 재분석은 받는다.';

-- 정상 결과로 반영하지 않은 콜백·조회 결과의 원문. 운영자가 원인을 확인하는 복구 대상이다.
CREATE TABLE unmatched_callback (
    callback_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kind VARCHAR(20) NOT NULL,
    reason VARCHAR(40) NOT NULL,
    request_id VARCHAR(255),
    job_id VARCHAR(255),
    detail TEXT,
    payload TEXT NOT NULL,
    received_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT unmatched_callback_pkey PRIMARY KEY (callback_id),
    CONSTRAINT unmatched_callback_reason_check
        CHECK (reason IN ('INVALID_BODY', 'UNKNOWN_REQUEST', 'ID_MISMATCH'))
);

COMMENT ON TABLE unmatched_callback IS
    '식별자가 맞지 않거나 필수 값이 빠져 정상 결과로 반영하지 않은 콜백. 받은 그대로 남기고 분석 서버에는 2xx로 답한다.';
COMMENT ON COLUMN unmatched_callback.kind IS 'VIDEO = 영상 분석 콜백.';
COMMENT ON COLUMN unmatched_callback.reason IS
    'INVALID_BODY = JSON이 아니거나 필수 필드·상태값·스키마 버전이 맞지 않음. UNKNOWN_REQUEST = 이 서버가 보낸 적 없는 요청. ID_MISMATCH = 요청은 찾았지만 세션·면접·사용자·영상·작업 id가 다름.';
COMMENT ON COLUMN unmatched_callback.payload IS '받은 본문 원문. JSON이 아니어도 그대로 둔다.';
