-- 원질문을 분석 결과에서 바로 꺼내 쓰던 것을, 종합 데이터(profile)로 만든 질문 풀에서 세트 단위로 꺼내 쓰도록 바꾼다.
--
-- 분석 서버는 자료를 한 번 분석해 종합 데이터를 만들고(/profile), 이 서버가 그것으로 질문 사이클을 요청한다
-- (/questions/cycle). 사이클 하나는 세트 3개다 -- 1:1은 세트당 5문항(15개), N:1은 세트당 2문항(6개).
-- 면접 하나가 세트 하나를 쓴다.

-- 같은 테이블에 옛 /generate 결과와 새 /profile 결과가 섞인다. 면접은 PROFILE만 쓴다.
ALTER TABLE analysis_data
    ADD COLUMN result_type VARCHAR(20) NOT NULL DEFAULT 'LEGACY_GENERATE';
ALTER TABLE analysis_data
    ADD CONSTRAINT analysis_data_result_type_check CHECK (result_type IN ('LEGACY_GENERATE', 'PROFILE'));

COMMENT ON COLUMN analysis_data.result_type IS
    'LEGACY_GENERATE = /generate 결과(result.interview[]). PROFILE = /profile 결과({ profile, projectSummary }).';

CREATE TABLE question_cycle (
    cycle_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    profile_job_id VARCHAR(255) NOT NULL,
    mode VARCHAR(10) NOT NULL,
    cycle_no INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    job_id VARCHAR(255),
    attempt INTEGER NOT NULL DEFAULT 1,
    requested_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6),
    error_message TEXT,
    CONSTRAINT question_cycle_pkey PRIMARY KEY (cycle_id),
    CONSTRAINT question_cycle_no_unique UNIQUE (profile_job_id, mode, cycle_no),
    CONSTRAINT question_cycle_mode_check CHECK (mode IN ('SOLO', 'MULTI')),
    CONSTRAINT question_cycle_status_check
        CHECK (status IN ('GENERATING', 'STANDBY', 'ACTIVE', 'EXHAUSTED', 'FAILED', 'RETIRED'))
);

CREATE UNIQUE INDEX question_cycle_job_id_unique ON question_cycle (job_id) WHERE job_id IS NOT NULL;
CREATE INDEX question_cycle_user_mode_idx ON question_cycle (user_id, mode);

COMMENT ON COLUMN question_cycle.profile_job_id IS '이 사이클을 만든 종합 데이터. analysis_data.job_id(result_type = PROFILE).';
COMMENT ON COLUMN question_cycle.status IS
    'GENERATING = 생성 요청 후 콜백 대기. STANDBY = 생성 완료, 대기본. ACTIVE = 지금 세트를 꺼내 쓰는 사이클(종합 데이터·모드당 하나). EXHAUSTED = 세트 3개를 모두 씀. FAILED = 생성 실패. RETIRED = 자료 변경으로 폐기.';
COMMENT ON COLUMN question_cycle.job_id IS '분석 서버가 접수하며 발급한 작업 id. 다시 요청하면 새 값으로 바뀐다.';
COMMENT ON COLUMN question_cycle.attempt IS
    '이번 요청이 몇 번째인지. 질문을 기다리는 면접이 있을 때 실패하면 한 번만 다시 요청한다.';

CREATE TABLE pool_question (
    question_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cycle_id BIGINT NOT NULL,
    set_no INTEGER NOT NULL,
    category VARCHAR(30) NOT NULL,
    question TEXT NOT NULL,
    intention TEXT NOT NULL,
    expected_answer TEXT,
    based_on JSONB,
    used_at TIMESTAMP(6),
    interview_id BIGINT,
    CONSTRAINT pool_question_pkey PRIMARY KEY (question_id),
    CONSTRAINT pool_question_set_no_check CHECK (set_no BETWEEN 1 AND 3)
);

CREATE INDEX pool_question_cycle_id_idx ON pool_question (cycle_id);
CREATE INDEX pool_question_interview_id_idx ON pool_question (interview_id) WHERE interview_id IS NOT NULL;

COMMENT ON COLUMN pool_question.intention IS '이 질문으로 확인하려는 것. 채점 기준이다.';
COMMENT ON COLUMN pool_question.expected_answer IS '모범답안. 꼬리질문 생성과 참고용이고 채점 기준은 아니다.';
COMMENT ON COLUMN pool_question.used_at IS '세트를 꺼낸 시각. 면접을 중간에 그만둬도 되돌리지 않는다.';

-- 꺼낼 세트가 없어 다음 사이클을 기다리는 면접 준비. 사이클 콜백이 이어서 진행한다.
ALTER TABLE question_tailor DROP CONSTRAINT question_tailor_status_check;
ALTER TABLE question_tailor
    ADD CONSTRAINT question_tailor_status_check CHECK (status IN ('WAITING', 'PENDING', 'SUCCEEDED', 'FAILED'));
CREATE INDEX question_tailor_waiting_idx ON question_tailor (user_id, mode) WHERE status = 'WAITING';
