CREATE TABLE feedback (
    feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    interview_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    job_id VARCHAR(64),
    status VARCHAR(255) NOT NULL,
    total_score INTEGER,
    intent_alignment_score INTEGER,
    reliability_score INTEGER,
    summary TEXT,
    strengths JSONB,
    improvements JSONB,
    frequent_words JSONB,
    answered_count INTEGER,
    question_count INTEGER,
    error_status_code INTEGER,
    error_message TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT feedback_pkey PRIMARY KEY (feedback_id),
    CONSTRAINT feedback_status_check CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED'))
);

CREATE INDEX feedback_interview_id_idx ON feedback (interview_id);
CREATE INDEX feedback_session_id_idx ON feedback (session_id);
CREATE UNIQUE INDEX feedback_job_id_unique ON feedback (job_id) WHERE job_id IS NOT NULL;

CREATE TABLE feedback_item (
    feedback_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    feedback_id BIGINT NOT NULL,
    question_id VARCHAR(64) NOT NULL,
    sort_order INTEGER NOT NULL,
    question_content TEXT,
    intention TEXT,
    user_answer TEXT,
    model_answer TEXT,
    strengths JSONB,
    improvements JSONB,
    comment TEXT,
    CONSTRAINT feedback_item_pkey PRIMARY KEY (feedback_item_id),
    CONSTRAINT feedback_item_feedback_fk FOREIGN KEY (feedback_id)
        REFERENCES feedback (feedback_id) ON DELETE CASCADE
);

CREATE INDEX feedback_item_feedback_id_idx ON feedback_item (feedback_id);
