CREATE TABLE question_tailor (
    tailor_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    interview_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    job_id VARCHAR(64),
    status VARCHAR(255) NOT NULL,
    tailored BOOLEAN,
    source_questions JSONB,
    questions JSONB,
    error_status_code INTEGER,
    error_message TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT question_tailor_pkey PRIMARY KEY (tailor_id),
    -- NOT_REQUESTED는 조회 응답에서만 쓰는 값이라 저장 대상이 아니다.
    CONSTRAINT question_tailor_status_check CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED'))
);

CREATE INDEX question_tailor_interview_id_idx ON question_tailor (interview_id);
CREATE UNIQUE INDEX question_tailor_job_id_unique ON question_tailor (job_id) WHERE job_id IS NOT NULL;
