-- N:1 면접(면접관 3인)을 담기 위한 스키마 변경.
-- 1:1 면접은 그대로 돌아가야 하므로 기존 컬럼은 지우지 않고 제약만 완화한다.

-- 페르소나에 직책 축을 신설한다.
-- 말투(type: FRIENDLY/NEUTRAL/STRESS)와 직책(role)은 독립이다. CEO가 압박형일 수도 친화형일 수도 있어야 한다.
ALTER TABLE persona
    ADD COLUMN role VARCHAR(255) NOT NULL DEFAULT 'TECH';

ALTER TABLE persona
    ADD CONSTRAINT persona_role_check CHECK (role IN ('TECH', 'HR', 'CEO'));

-- major(BACKEND/FRONTEND)는 기술 면접관의 세부 전공이다. 인사팀·CEO에게는 해당 값이 없다.
ALTER TABLE persona
    ALTER COLUMN major DROP NOT NULL;

ALTER TABLE persona
    ADD CONSTRAINT persona_tech_major_check CHECK (role <> 'TECH' OR major IS NOT NULL);

-- 면접 방식. 기존 면접은 전부 1:1이다.
ALTER TABLE interview
    ADD COLUMN mode VARCHAR(255) NOT NULL DEFAULT 'SOLO';

ALTER TABLE interview
    ADD CONSTRAINT interview_mode_check CHECK (mode IN ('SOLO', 'MULTI'));

-- N:1은 면접관이 여럿이라 단일 컬럼으로 표현할 수 없다. 1:1 호환을 위해 컬럼은 남기고 NOT NULL만 푼다.
ALTER TABLE interview
    ALTER COLUMN persona_id DROP NOT NULL;

-- 면접에 참여하는 면접관 목록. persona_order가 면접 진행 순서다(TECH -> HR -> CEO).
CREATE TABLE interview_persona (
    interview_persona_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    interview_id BIGINT NOT NULL,
    persona_id BIGINT NOT NULL,
    persona_order INTEGER NOT NULL,
    CONSTRAINT interview_persona_pkey PRIMARY KEY (interview_persona_id),
    CONSTRAINT interview_persona_interview_fk FOREIGN KEY (interview_id)
        REFERENCES interview (interview_id) ON DELETE CASCADE,
    CONSTRAINT interview_persona_order_unique UNIQUE (interview_id, persona_order),
    CONSTRAINT interview_persona_unique UNIQUE (interview_id, persona_id)
);

CREATE INDEX interview_persona_interview_id_idx ON interview_persona (interview_id);

-- 어느 면접관이 던진 질문인지. 1:1 질문에는 값이 없다.
ALTER TABLE interview_question
    ADD COLUMN persona_id BIGINT;

-- 모의면접 답변으로 255자는 짧다. 잘린 답변은 그대로 피드백 품질로 이어진다.
ALTER TABLE interview_answer
    ALTER COLUMN content TYPE TEXT;

-- 면접관별 종합 피드백. N:1에만 생기는 계층이라 별도 테이블로 둔다.
-- 문항이 페르소나당 2~3개뿐이라 3지표(total/intent/reliability)는 두지 않고 점수 하나만 둔다.
CREATE TABLE feedback_persona (
    feedback_persona_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    feedback_id BIGINT NOT NULL,
    persona_id BIGINT,
    persona_role VARCHAR(255),
    sort_order INTEGER NOT NULL,
    score INTEGER,
    comment TEXT,
    strengths JSONB,
    improvements JSONB,
    answered_count INTEGER,
    question_count INTEGER,
    CONSTRAINT feedback_persona_pkey PRIMARY KEY (feedback_persona_id),
    CONSTRAINT feedback_persona_feedback_fk FOREIGN KEY (feedback_id)
        REFERENCES feedback (feedback_id) ON DELETE CASCADE
);

CREATE INDEX feedback_persona_feedback_id_idx ON feedback_persona (feedback_id);

-- 문항별 피드백이 어느 면접관 것인지. 1:1 피드백에는 값이 없다.
ALTER TABLE feedback_item
    ADD COLUMN persona_id BIGINT;
